apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradevis-frontend
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tradevis-frontend
  template:
    metadata:
      labels:
        app: tradevis-frontend
    spec:
      containers:
      - name: tradevis-frontend
        image: roeilevinson/tradevis-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tradevis-frontend
  namespace: app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: tradevis-frontend