apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradevis-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: roeilevinson/tradevis-frontend:latest
    argocd-image-updater.argoproj.io/roeilevinson/tradevis-frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/roeilevinson/tradevis-frontend.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/tradevisapp/app.git
    targetRevision: HEAD
    path: kube-app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 