apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tradevis-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tradevisapp/app.git
    targetRevision: HEAD
    path: helm-charts/tradevis
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 