apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false" # Disable HTTPS redirect if no TLS
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Ensure HTTPS is used for ArgoCD
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.tradevis.click  # Your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80  # Matches the service port
