# Default values for the TradeVis application
nameOverride: ""
fullnameOverride: ""
# Deployment configurations
deployment:
  name: tradevis-frontend
  replicas: 2
# Image configurations
image:
  repository: roeilevinson/tradevis-frontend
  tag: v0.1.19
  pullPolicy: Always
# Service configurations
service:
  type: ClusterIP
  port: 80
  targetPort: 80
  nodePort: 30080
# Ingress configuration
ingress:
  enabled: true
  className: nginx
  host: ""
# Namespace configuration
namespace: app
# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
