{{- if .Values.auth0.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  domain: {{ env "AUTH0_DOMAIN" }}
  audience: {{ env "AUTH0_AUDIENCE" }}
  client-secret: {{ env "AUTH0_CLIENT_SECRET" }}
{{- end }} 