{{- if .Values.auth0.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  domain: {{ .Values.auth0.domain | quote }}
  audience: {{ .Values.auth0.audience | quote }}
  client-secret: {{ .Values.auth0.clientSecret | quote }}
{{- end }} 