{{- if .Values.auth0.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  domain: {{ .Values.auth0.domain | b64enc }}
  audience: {{ .Values.auth0.audience | b64enc }}
  client-secret: {{ .Values.auth0.clientSecret | b64enc }}
{{- end }} 